image: Visual Studio 2019   # на этом VM-образе установлены все Visual Studio с 2008 по 2015

shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

matrix:
    fast_finish: false           # не останавливаемся после возникновения ошибки в каком-то из заданий

platform:
    # будем гонять пока CI на amd64 
    - x64
    # - x86

configuration:
    # ... и в дебажной, и в релизной конфигурациях ...
    - Debug
    - Release

before_build:
    - cmake -G "Visual Studio 16 2019 Win64" .

install:

    # - appveyor DownloadFile <url> -FileName <local-file>
    # - 7z e -y <local-file> -o<local-dir>


build_script:
    - cmd: >-
      mkdir build
      cd build
      cmake c:\develop\src\RecoveryTools -G "Visual Studio 16"
      cmake build . --config "Debug"

# test_script:
#     # скрипт тестирования проекта:
#     - ctest -C %CONFIGURATION% --output-on-failure

# artifacts:
#     - path: <local-package-path>
#       name: RecoveryTools

deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: VDH2H+21K8+YeJhBrJ/OcA==

    artifact: RecoveryTools
    force_update: true

    on:
        appveyor_repo_tag: true