image: Visual Studio 2019   


build_script:
      mkdir build
      cd build
      cmake c:\develop\src\RecoveryTools -G "Visual Studio 16"
      cmake build . --config "Debug"

# test_script:
#     # скрипт тестирования проекта:
#     - ctest -C %CONFIGURATION% --output-on-failure

# artifacts:
#     - path: <local-package-path>
#       name: RecoveryTools

deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: VDH2H+21K8+YeJhBrJ/OcA==

    artifact: RecoveryTools
    force_update: true

    on:
        appveyor_repo_tag: true